# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1426259ec9f55d37a206792971b999eac2537b742d2fb11fb75c0f564fe5ce04fd13c7d1aead752d243c2674a3f1cb5488cb9de517f190dd8ad25f17c7c6c4bf

test:
  secret_key_base: c58a20b53cd950485eafda15bf6689a6e3e48676503ba4da525d0873037218d9b6a1b8687ae347c183b6fc5121bf60c549fe9f0d1842043485689f27f61a6b6b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
